Repository dracidoupe/graveyard, pull requests merged in 2021-07, with the labels that each got.

#321 Escape user input in a way compatible with the old version (refs #320)
  ddcz/text.py
  ddcz/views/comments.py
  ddcz/views/tavern.py
Labels: security

#326 For mismatched pair HTML tags, encode the inner tag (refs #182)
  ddcz/html.py
  ddcz/tests/test_html.py
Labels: data-quality

#334 Provide a migration to fake for fixing botched notice board id migration (fixes #309)
  ddcz/migrations/0101_remove_taverntablenoticeboard_id.py
Labels: data-quality, infrastructure

#338 Fix production cache config (refs #197)
  ddcz/views/news.py
  graveyard/settings/base.py
  graveyard/settings/production.py
Labels: infrastructure, speedup

#351 Datetime attribute fixed
  ddcz/templates/creative-pages/alchemisttool-detail.html
  ddcz/templates/creative-pages/alchemisttool-list.html
  ddcz/templates/creative-pages/commonarticle-detail.html
  ddcz/templates/creative-pages/commonarticle-list.html
  ddcz/templates/creative-pages/downloaditem-detail.html
  ddcz/templates/creative-pages/downloaditem-list.html
  ddcz/templates/creative-pages/gallerypicture-detail.html
  ddcz/templates/creative-pages/gallerypicture-list.html
  ddcz/templates/creative-pages/item-detail.html
  ddcz/templates/creative-pages/item-list.html
  ddcz/templates/creative-pages/monster-detail.html
  ddcz/templates/creative-pages/monster-list.html
  ddcz/templates/creative-pages/quest-list.html
  ddcz/templates/creative-pages/rangerspell-detail.html
  ddcz/templates/creative-pages/rangerspell-list.html
  ddcz/templates/creative-pages/skill-detail.html
  ddcz/templates/creative-pages/skill-list.html
  ddcz/templates/creative-pages/wizardspell-detail.html
  ddcz/templates/creative-pages/wizardspell-list.html
Labels: ready
